FROM python:3.12-slim

RUN pip install --no-cache-dir dagster dagster-webserver dagster-postgres

ENV DAGSTER_HOME=/opt/dagster/dagster_home
RUN mkdir -p $DAGSTER_HOME

COPY dagster.yaml workspace.yaml $DAGSTER_HOME/

WORKDIR /opt/dagster
